graphql:
  packages: "com.elisapolystar.blueprints.graphql"
  print-schema: true
  playground:
    enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blueprints
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

management:
    endpoint:
      health:
        probes:
          enabled: true
          add-additional-paths: true
        show-details: always
    health:
      readinessstate:
        enabled: true
      livenessstate:
        enabled: true
      diskspace:
        enabled: true
      db:
        enabled: true
      ping:
        enabled: true
