services:
  postgres:
    image: postgres:16.4-alpine3.20
    user: postgres
    volumes:
      - /var/lib/postgresql/data
    command: postgres -N 300
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - backend

networks:
  backend:
